CREATE TABLE Client (
  id IDENTITY  PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL CHECK
    (CHAR_LENGTH(NAME)>3 and CHAR_LENGTH(NAME)<201)
);

CREATE TABLE Planet(
  id VARCHAR(10) PRIMARY KEY CHECK (id ~ '^[A-Z0-9]+$'),
  name VARCHAR(500) NOT NULL
);

CREATE TABLE Ticket(
  id IDENTITY  PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  client_id INTEGER NOT NULL,
  from_planet_id VARCHAR(500) NOT NULL,
  to_planet_id VARCHAR(500) NOT NULL
);

ALTER TABLE TICKET
   ADD  FOREIGN KEY (client_id)
      REFERENCES CLIENT(id)
      ON DELETE CASCADE;
ALTER TABLE TICKET
   ADD  FOREIGN KEY (from_planet_id)
      REFERENCES PLANET(id)
      ON DELETE CASCADE;
ALTER TABLE TICKET
     ADD  FOREIGN KEY (to_planet_id)
        REFERENCES PLANET(id)
        ON DELETE CASCADE;